# fly.toml app configuration file generated for fso-notes-1515 on 2023-07-07T10:05:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-notes-1515"
primary_region = "yyz"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
